language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - pylint pypyt
    - coverage run --source pypyt -m pytest
    - coverage report -m

after_success:
    - coveralls